DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUS_SQ;

CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(2),
    LEVELNAME VARCHAR(10) NOT NULL,
    PRIMARY KEY (LEVELNO));
    
CREATE SEQUENCE CUS_SQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE CUSTOMER(
    CNO NUMBER(4),
    CNAME VARCHAR(50) NOT NULL,
    JOINDATE DATE DEFAULT TO_DATE(SYSDATE, 'YYYY-MM-DD'),
    PHONE VARCHAR(30),
    POINT NUMBER(8),
    LEVELNO NUMBER(2) NOT NULL,
    PRIMARY KEY (CNO),
    FOREIGN KEY (LEVELNO) REFERENCES CUS_LEVEL (LEVELNO),
    UNIQUE (PHONE));

INSERT INTO CUS_LEVEL
    VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL
    VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL
    VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL
    VALUES (4, 'BLACK');

INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNO)
    VALUES (CUS_SQ.NEXTVAL, 'È«±æµ¿', TO_DATE('21/06/10', 'YY/MM/DD'),
            '010-9999-9999', 0, 1);
INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, LEVELNO)
    VALUES (CUS_SQ.NEXTVAL, 'ÀÌÃ¶¼ö', TO_DATE('20/11/12', 'YY/MM/DD'),
            '010-8888-8888', 2);
            
UPDATE CUSTOMER 
    SET POINT = POINT + 300
    WHERE CNAME = 'È«±æµ¿';
    
UPDATE CUSTOMER
    SET JOINDATE = TO_DATE('16/09/06', 'YY-MM-DD'),
        PHONE = '010-9999-9888'    
    WHERE CNAME = 'ÀÌÃ¶¼ö';

SELECT CNO, CNAME, TO_CHAR(JOINDATE, 'YYYY-MM-DD') JOINDATE , 
        PHONE, POINT, LEVELNAME
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO;


