-- 연습문제 PDF.01 

-- 1번
CREATE TABLE MY_DATA(
    ID NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(10),
    USERID VARCHAR2(30),
    SALARY NUMBER(10, 2));
SELECT * FROM MY_DATA;
DESC MY_DATA;

-- 2번
INSERT INTO MY_DATA 
    VALUES (1, 'SCOTT', 'SSCOTT', 10000);
INSERT INTO MY_DATA 
    VALUES (2, 'FORD', 'FFORD', 13000);
INSERT INTO MY_DATA 
    VALUES (3, 'PATEL', 'PPATEL', 33000);
INSERT INTO MY_DATA (ID, NAME, USERID, SALARY)
    VALUES (4, 'REPORT', 'RREPORT', 23500);
INSERT INTO MY_DATA (ID, NAME, USERID, SALARY)
    VALUES (5, 'GOOD', 'GGOOD', 44450);

-- 3번
SELECT ID, NAME, USERID, TO_CHAR(SALARY, '99,999.99') "SALARY" 
    FROM MY_DATA;

-- 4번
COMMIT;

-- 6번
UPDATE MY_DATA 
    SET SALARY = 65000
    WHERE ID = 3;
SELECT * FROM MY_DATA;
COMMIT;

-- 7번
DELETE FROM MY_DATA
    WHERE NAME = 'FORD';
    
-- 8번
UPDATE MY_DATA
    SET SALARY = 15000
    WHERE SALARY <= 15000;
    
-- 9번
DROP TABLE MY_DATA;


