-- DROP
DROP TABLE STUDENT;
DROP TABLE MAJOR;
DROP SEQUENCE STUDENT_SQ;

-- CREATE
CREATE TABLE MAJOR(
    MNO NUMBER(2),
    MNAME VARCHAR2(50) NOT NULL,
    PRIMARY KEY(mNO));
CREATE TABLE STUDENT(
    SNO VARCHAR2(7),
    SNAME VARCHAR2(30) NOT NULL,
    MNO NUMBER(2) NOT NULL,
    SCORE NUMBER(3),
    SEXPEL NUMBER(1) DEFAULT 0 CHECK(SEXPEL=0 OR SEXPEL=1),
    PRIMARY KEY(SNO),
    FOREIGN KEY(MNO) REFERENCES MAJOR(MNO));
CREATE SEQUENCE STUDENT_SQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
    
-- 학과 입력
INSERT INTO MAJOR VALUES(1, '빅데이터학');
INSERT INTO MAJOR VALUES(2, '경영정보학');
INSERT INTO MAJOR VALUES(3, '컴퓨터공학');
INSERT INTO MAJOR VALUES(4, '정보통신학');
INSERT INTO MAJOR VALUES(5, '인공지능학');

SELECT * FROM STUDENT;
-- 학번검색
SELECT SNAME, MNAME, SCORE
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO AND SNO = 2021008;
    
-- 이름검색
SELECT SNO, SNAME, MNAME, SCORE
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO AND SNAME = '홍길동';

-- 전공검색
SELECT ROWNUM||'등' RANK, A.* 
    FROM (SELECT SNAME, MNAME ||'('|| M.MNO ||')' MNAMEMNO, SCORE 
                FROM STUDENT S, MAJOR M 
                WHERE S.MNO = M.MNO AND MNAME = '빅데이터학' AND SEXPEL = 0
                ORDER BY SCORE DESC) A;

-- 학생입력
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE)
    VALUES (TO_CHAR(SYSDATE, 'YYYY') || TRIM(TO_CHAR(STUDENT_SQ.NEXTVAL, '000')),
            '홍길동', 1, 60);

INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE)
    VALUES (TO_CHAR(SYSDATE, 'YYYY') || TRIM(TO_CHAR(STUDENT_SQ.NEXTVAL, '000')),
            '박하나', (SELECT MNO FROM MAJOR WHERE MNAME = '빅데이터학'), 60);            
            
SELECT MNO FROM MAJOR WHERE MNAME = '빅데이터학';
    
            
    
-- 학생수정
UPDATE STUDENT SET SCORE = 90 WHERE SNO = 2021009;

-- 학생출력(제적제외)
SELECT ROWNUM||'등' RANK, A.* 
    FROM (SELECT SNAME, MNAME ||'('|| M.MNO ||')' MNAMEMNO, SCORE 
                FROM STUDENT S, MAJOR M 
                WHERE S.MNO = M.MNO AND SEXPEL = 0
                ORDER BY SCORE DESC) A;
 
 -- 제적자출력
SELECT ROWNUM||'등' RANK, A.* 
    FROM (SELECT SNAME, MNAME ||'('|| M.MNO ||')' MNAMEMNO, SCORE 
                FROM STUDENT S, MAJOR M 
                WHERE S.MNO = M.MNO AND SEXPEL = 1
                ORDER BY SCORE DESC) A;   

-- 제적처리
UPDATE STUDENT SET SEXPEL = 1 WHERE SNAME = '홍길동';





SELECT TO_CHAR(SYSDATE, 'YYYY') || TRIM(TO_CHAR(STUDENT_SQ.NEXTVAL, '000')) FROM DUAL;
SELECT * FROM STUDENT;
SELECT * FROM MAJOR;


SELECT MNAME FROM MAJOR;

COMMIT;



    